In [18]:
import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape)

arr1.ndim


[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


1

In [4]:
arr2 = np.array([1,2,3,4])
arr2.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [19]:
arr3 = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr3)
print(type(arr3))
print(arr3.shape)
arr3.size

[[1 2 3 4 5]
 [5 6 7 8 9]]
<class 'numpy.ndarray'>
(2, 5)


10

In [11]:
arr4 = np.arange(0,11,2)
print(arr4)
arr4.reshape(6,1)

[ 0  2  4  6  8 10]


array([[ 0],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10]])

In [14]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr1+arr2)

[ 7  9 11 13 15]


In [28]:
data = np.array([1,2,3,4,5])

mean = np.mean(data)
std = np.std(data)
median = np.median(data)
variance = np.var(data)

normalized_data = (data-mean)/std

print("mean: ", mean)
print("std: ", std)
print("median: ", median)
print("variance: ", variance)

print("normalized_data: ", normalized_data)

mean:  3.0
std:  1.4142135623730951
median:  3.0
variance:  2.0
normalized_data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [30]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])